version: "3.8"
services:
  app: &app_base
    build:
      context: ./rails
      dockerfile: ./Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /var/tmp
      - ./rails:/app
      - /app/tmp
      - /app/log
      - /app/.git
      - /app/vendor
      - /node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - db
    networks: 
      - app-net
  db:
    image: postgres:latest
    ports: 
      - "8080:8080"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: db
    volumes: 
      - /var/lib/postgresql/data
    networks: 
      - app-net
networks:
  app-net:
    driver: bridge